# Upload a Python Package using Twine when a semver tag is pushed to
# the default branch
#
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to PyPI and GH Pages

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install doc dependencies in venv
      run: |
        make install install-docs

    - name: build docs
      shell: bash
      run: |
        (source venv/bin/activate && make doc-build)

    - name: publish docs to GH pages
      shell: bash
      run: |
        git config --local user.email "publish@gha"
        git config --local user.name "frost publish-gh-pages GHA"

        mv -f docs/_build/html/* .
        git add .
        git commit -vm "build docs for gh-page for commit ${{ github.sha }}"
        git push -f origin HEAD:gh-pages

  publish-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install publish dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install package dependencies
      run: |
        pip install -r requirements.txt

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
